openapi: 3.2.0
info:
  title: Legato Service Catalog Event Subscription Hub API
  version: 4.0.0-RC
  description: "The Service Catalog API provides a standardized mechanism for retrieving \n*ServiceSpecifications*. Using these APIs Business Applications (BUS) \nsystems query the **Service Catalog** for *ServiceSpecifications* supported \nby the Service Orchestration Function (SOF).\n\nAdditionally, the APIs also allow the BUS to register listeners to be \nnotified of the changes to the *ServiceSpecifications*.  \n\n- MEF Developer Guide Reference : MEF_W99 v1.0\n\n- TMF API Reference : TMF 633 v18.5.1\n\nCopyright © MEF 2020. All Rights Reserved\n\nThis file includes content based on the TM Forum Service Catalog Management API\n(TMF633 v3.0.0) available at\nhttps://github.com/tmforum-apis/TMF633_ServiceCatalog, which is licensed\nby the TM Forum under the Apache License version 2.0. Such content has been\nmodified by the MEF Forum and its contributors."
servers:
- url: https://{server}:{port}{basePath}
  variables:
    server:
      default: mef.net
    port:
      enum:
      - '8443'
      - '443'
      default: '8443'
    basePath:
      default: /mefApi/legato/serviceCatalog/v4
tags:
- name: EventSubscriptionHub
  description: Mechanisms for BUS to subscribe/unsubscribe to *Notifications*.
paths:
  /hub:
    post:
      tags:
      - EventSubscriptionHub
      operationId: hubCreate
      summary: Create Hub
      description: Structure used to create a hub (to subscribe to notification
      deprecated: false
      requestBody:
        content:
          application/json;charset=utf-8:
            schema:
              $ref: ../common/hubSchema.openapi.yaml#/components/schemas/EventSubscriptionInput
        required: true
      responses:
        '201':
          description: Created
          content:
            application/json;charset=utf-8:
              schema:
                $ref: ../common/hubSchema.openapi.yaml#/components/schemas/EventSubscription
        '400':
          $ref: ../common/errorSchema.openapi.yaml#/components/responses/BadRequest
        '401':
          $ref: ../common/errorSchema.openapi.yaml#/components/responses/Unauthorized
        '403':
          $ref: ../common/errorSchema.openapi.yaml#/components/responses/Forbidden
        '404':
          $ref: ../common/errorSchema.openapi.yaml#/components/responses/NotFound
        '405':
          $ref: ../common/errorSchema.openapi.yaml#/components/responses/MethodNotAllowed
        '408':
          $ref: ../common/errorSchema.openapi.yaml#/components/responses/RequestTimeout
        '409':
          $ref: ../common/errorSchema.openapi.yaml#/components/responses/Conflict
        '500':
          $ref: ../common/errorSchema.openapi.yaml#/components/responses/InternalServerError
        '503':
          $ref: ../common/errorSchema.openapi.yaml#/components/responses/ServiceUnavailable
  /hub/{hubId}:
    get:
      tags:
      - EventSubscriptionHub
      operationId: hubGet
      summary: get hub
      description: ''
      deprecated: false
      parameters:
      - name: hubId
        required: true
        in: path
        schema:
          type: string
      responses:
        '200':
          description: Ok
          content:
            application/json;charset=utf-8:
              schema:
                $ref: ../common/hubSchema.openapi.yaml#/components/schemas/EventSubscription
        '400':
          $ref: ../common/errorSchema.openapi.yaml#/components/responses/BadRequest
        '401':
          $ref: ../common/errorSchema.openapi.yaml#/components/responses/Unauthorized
        '403':
          $ref: ../common/errorSchema.openapi.yaml#/components/responses/Forbidden
        '404':
          $ref: ../common/errorSchema.openapi.yaml#/components/responses/NotFound
        '405':
          $ref: ../common/errorSchema.openapi.yaml#/components/responses/MethodNotAllowed
        '408':
          $ref: ../common/errorSchema.openapi.yaml#/components/responses/RequestTimeout
        '422':
          $ref: ../common/errorSchema.openapi.yaml#/components/responses/UnprocessableEntity
        '500':
          $ref: ../common/errorSchema.openapi.yaml#/components/responses/InternalServerError
        '503':
          $ref: ../common/errorSchema.openapi.yaml#/components/responses/ServiceUnavailable
    delete:
      tags:
      - EventSubscriptionHub
      operationId: hubDelete
      summary: Delete Hub
      description: Delete an existing Hub
      deprecated: false
      parameters:
      - name: hubId
        required: true
        in: path
        schema:
          type: string
      responses:
        '204':
          description: No Content
        '400':
          $ref: ../common/errorSchema.openapi.yaml#/components/responses/BadRequest
        '401':
          $ref: ../common/errorSchema.openapi.yaml#/components/responses/Unauthorized
        '403':
          $ref: ../common/errorSchema.openapi.yaml#/components/responses/Forbidden
        '404':
          $ref: ../common/errorSchema.openapi.yaml#/components/responses/NotFound
        '405':
          $ref: ../common/errorSchema.openapi.yaml#/components/responses/MethodNotAllowed
        '408':
          $ref: ../common/errorSchema.openapi.yaml#/components/responses/RequestTimeout
        '422':
          $ref: ../common/errorSchema.openapi.yaml#/components/responses/UnprocessableEntity
        '500':
          $ref: ../common/errorSchema.openapi.yaml#/components/responses/InternalServerError
        '503':
          $ref: ../common/errorSchema.openapi.yaml#/components/responses/ServiceUnavailable
