openapi: 3.2.0
info:
  title: Legato Service Catalog Service Specification API
  version: 4.0.0-RC
  description: "The Service Catalog API provides a standardized mechanism for retrieving \n*ServiceSpecifications*. Using these APIs Business Applications (BUS) \nsystems query the **Service Catalog** for *ServiceSpecifications* supported \nby the Service Orchestration Function (SOF).\n\nAdditionally, the APIs also allow the BUS to register listeners to be \nnotified of the changes to the *ServiceSpecifications*.  \n\n- MEF Developer Guide Reference : MEF_W99 v1.0\n\n- TMF API Reference : TMF 633 v18.5.1\n\nCopyright © MEF 2020. All Rights Reserved\n\nThis file includes content based on the TM Forum Service Catalog Management API\n(TMF633 v3.0.0) available at\nhttps://github.com/tmforum-apis/TMF633_ServiceCatalog, which is licensed\nby the TM Forum under the Apache License version 2.0. Such content has been\nmodified by the MEF Forum and its contributors."
servers:
- url: https://{server}:{port}{basePath}
  variables:
    server:
      default: mef.net
    port:
      enum:
      - '8443'
      - '443'
      default: '8443'
    basePath:
      default: /mefApi/legato/serviceCatalog/v4
tags:
- name: ServiceSpecification
  description: Mechanisms for BUS to query and retrieve *ServiceSpecifications*.
paths:
  /serviceSpecification:
    get:
      tags:
      - ServiceSpecification
      operationId: serviceSpecificationFind
      summary: List service specifications
      description: This operation returns service specifications from a catalog
      deprecated: false
      parameters:
      - name: category
        required: false
        in: query
        description: Service Category
        schema:
          type: string
      - name: lifecycleStatus
        required: false
        in: query
        description: Service Specification status
        schema:
          $ref: serviceCatalogSchema.openapi.yaml#/components/schemas/ServiceSpecificationState
      - name: fields
        required: false
        in: query
        description: "Comma-separated properties of the Service Specification to be \nincluded in the returned response"
        schema:
          type: string
      - name: offset
        required: false
        in: query
        description: "Requested start index in a ordered list (sorted by id property) of \nmatching Service Specifications to be provided in response. "
        schema:
          type: integer
      - name: limit
        required: false
        in: query
        description: "Requested maximum number of Service Specifications to be provided \nin the response"
        schema:
          type: integer
      responses:
        '200':
          description: Ok
          content:
            application/json;charset=utf-8:
              schema:
                type: array
                items:
                  $ref: serviceCatalogSchema.openapi.yaml#/components/schemas/ServiceSpecification
        '400':
          $ref: ../common/errorSchema.openapi.yaml#/components/responses/BadRequest
        '401':
          $ref: ../common/errorSchema.openapi.yaml#/components/responses/Unauthorized
        '403':
          $ref: ../common/errorSchema.openapi.yaml#/components/responses/Forbidden
        '404':
          $ref: ../common/errorSchema.openapi.yaml#/components/responses/NotFound
        '422':
          $ref: ../common/errorSchema.openapi.yaml#/components/responses/UnprocessableEntity
        '500':
          $ref: ../common/errorSchema.openapi.yaml#/components/responses/InternalServerError
        '503':
          $ref: ../common/errorSchema.openapi.yaml#/components/responses/ServiceUnavailable
  /serviceSpecification/{id}:
    get:
      tags:
      - ServiceSpecification
      operationId: serviceSpecificationGet
      summary: Retrieve a service specification
      description: This operation returns a service specification by its id from a catalog. Attribute selection is enabled using the fields attribute.
      deprecated: false
      parameters:
      - name: id
        required: true
        in: path
        description: Identifier of the ServiceSpecification
        schema:
          type: string
      - name: fields
        required: false
        in: query
        description: "Comma-separated properties of the Service Specification to be \nincluded in the returned response"
        schema:
          type: string
      responses:
        '200':
          description: Ok
          content:
            application/json;charset=utf-8:
              schema:
                $ref: serviceCatalogSchema.openapi.yaml#/components/schemas/ServiceSpecification
        '400':
          $ref: ../common/errorSchema.openapi.yaml#/components/responses/BadRequest
        '401':
          $ref: ../common/errorSchema.openapi.yaml#/components/responses/Unauthorized
        '403':
          $ref: ../common/errorSchema.openapi.yaml#/components/responses/Forbidden
        '404':
          $ref: ../common/errorSchema.openapi.yaml#/components/responses/NotFound
        '405':
          $ref: ../common/errorSchema.openapi.yaml#/components/responses/MethodNotAllowed
        '408':
          $ref: ../common/errorSchema.openapi.yaml#/components/responses/RequestTimeout
        '422':
          $ref: ../common/errorSchema.openapi.yaml#/components/responses/UnprocessableEntity
        '500':
          $ref: ../common/errorSchema.openapi.yaml#/components/responses/InternalServerError
        '503':
          $ref: ../common/errorSchema.openapi.yaml#/components/responses/ServiceUnavailable
